// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRsFCcRDh55reUmjc37pNAWIWpcQcm-0',
    appId: '1:583224826951:web:d0446c5bf9aaa1fc222562',
    messagingSenderId: '583224826951',
    projectId: 'chat-app-f91e7',
    authDomain: 'chat-app-f91e7.firebaseapp.com',
    storageBucket: 'chat-app-f91e7.appspot.com',
    measurementId: 'G-HSTWKS3MLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATKZUBD3HAb9T1-ow5N8zmoZdPioYZMjg',
    appId: '1:583224826951:android:029937d82562687a222562',
    messagingSenderId: '583224826951',
    projectId: 'chat-app-f91e7',
    storageBucket: 'chat-app-f91e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDarjoT0LGcMrTP0Id4JfghSrqgiyOB8kk',
    appId: '1:583224826951:ios:f8c8bb9d2dce1633222562',
    messagingSenderId: '583224826951',
    projectId: 'chat-app-f91e7',
    storageBucket: 'chat-app-f91e7.appspot.com',
    androidClientId: '583224826951-rlpjem8h79vdt71t0gidi04thgmo80ge.apps.googleusercontent.com',
    iosClientId: '583224826951-p3g7q56fm1uthfqiv8ccdg7tsfooogdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDarjoT0LGcMrTP0Id4JfghSrqgiyOB8kk',
    appId: '1:583224826951:ios:f8c8bb9d2dce1633222562',
    messagingSenderId: '583224826951',
    projectId: 'chat-app-f91e7',
    storageBucket: 'chat-app-f91e7.appspot.com',
    androidClientId: '583224826951-rlpjem8h79vdt71t0gidi04thgmo80ge.apps.googleusercontent.com',
    iosClientId: '583224826951-p3g7q56fm1uthfqiv8ccdg7tsfooogdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
